"""empty message

Revision ID: 264077c6fe31
Revises: 0d770fb0f2c7
Create Date: 2020-04-22 22:43:56.943799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '264077c6fe31'
down_revision = '0d770fb0f2c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'num_upcoming_shows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('num_upcoming_shows', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
