"""empty message

Revision ID: 7921b089ff18
Revises: 5ddd5507c66e
Create Date: 2020-04-22 05:42:07.486917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7921b089ff18'
down_revision = '5ddd5507c66e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'num_upcoming_shows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('num_upcoming_shows', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
