"""empty message

Revision ID: 9e51ff09e17d
Revises: 7ac1d1f34f23
Create Date: 2020-04-21 00:11:43.223051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e51ff09e17d'
down_revision = '7ac1d1f34f23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('venue_name', sa.String(length=120), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('artist_name', sa.String(length=120), nullable=True),
    sa.Column('artist_image_link', sa.String(length=120), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Show')
    # ### end Alembic commands ###
